server {
    listen 80;
    server_name office.vinicius-gpl.com;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;         
	proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_hide_header X-Frame-Options;
        proxy_redirect http:// https://;        
	add_header Cross-Origin-Resource-Policy "cross-origin" always;
	add_header Cross-Origin-Embedder-Policy "unsafe-none" always;
        add_header Content-Security-Policy "frame-ancestors https://nextcloud.vinicius-gpl.com" always;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
        client_max_body_size 200M;
    }
}
