server {
  listen 80;
  server_name _;

  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  # Health Check
  location /health {
    access_log off;
    return 200 "healthy\n";
  }

  # Importa a config do seu App (/siaap)
  include /etc/nginx/conf.d/apps/*.conf;
}
