networks:
  proxy:
    external: true

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/caddy/caddyfile:/etc/caddy/Caddyfile
      - /opt/caddy/conf.d:/etc/caddy/conf.d
      - caddy-config:/config
      - caddy-data:/data
      - /opt/caddy/static:/srv/static:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy

volumes:
  caddy-data:
    name: caddy-data
  caddy-config:
    name: caddy-config
