# Redirecionamento de raiz
location = /siaap {
  return 301 /siaap/;
}

location /siaap/ {
  proxy_pass http://siaap;
  proxy_http_version 1.1;

  # Headers
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Prefix /siaap;

  # Websockets
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $connection_upgrade;

  # Sub Filters (Vite/Assets fixes)
  sub_filter_once off;
  sub_filter_types application/javascript;
  proxy_set_header Accept-Encoding "";

  sub_filter '"/assets/' '"/siaap/assets/';
  sub_filter "'/assets/" "'/siaap/assets/";

  sub_filter '"/v1/api/' '"/siaap/v1/api/';
  sub_filter "'/v1/api/" "'/siaap/v1/api/";

  proxy_redirect off;
}

# Tratamento específico da API solta na raiz (Legacy support via Referer)
location /v1/api/ {
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Prefix /siaap;

  if ($http_referer ~* /siaap/) {
      rewrite ^/(.*)$ /siaap/$1 break;
      proxy_pass http://siaap;
  }
}
