services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Sao_paulo"
      TRANSMISSION_WEB_ALLOWEDORIGINS: "*"
    ports:
      - "9092:9091"
    volumes:
      - ~/.docker/transmission/data:/config:Z
      - ~/.docker/transmission/downloads:/downloads:Z
      - ~/.docker/transmission/watch/folder:/watch:Z
    restart: unless-stopped
