services:
  portainer_agent:
    image: docker.io/portainer/agent:2.39.1
    container_name: portainer-agent
    restart: always
    privileged: true
    ports:
      - "9002:9001"
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z
      - /:/host:ro,rslave
