[relay_servers]
192.168.0.1 ansible_user=root ansible_ssh_forward_agent=true email=contato@acerola-comic.com domain=acerola-comic.com beszel_key=CHAVE_PUBLICA_GERADA_PELO_HUB wireguard_clients='[{"name":"windows","pubkey":"CHAVE_PUBLICA_WINDOWS"},{"name":"phone","pubkey":"CHAVE_PUBLICA_CELULAR"}]'
