services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    volumes:
      - ./config/authelia:/config
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9091/api/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.vinicius-gpl.com`)
      - traefik.http.routers.authelia.entrypoints=web
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      - traefik.http.middlewares.authelia-forwardauth.forwardauth.address=http://authelia:9091/api/authz/forward-auth
      - traefik.http.middlewares.authelia-forwardauth.forwardauth.trustforwardheader=true
      - traefik.http.middlewares.authelia-forwardauth.forwardauth.authresponseheaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name

  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    command:
     - --api.dashboard=true
     - --api.insecure=false
     - --providers.docker=true
     - --providers.docker.exposedbydefault=false
     - --providers.file.directory=/etc/traefik/dynamic
     - --providers.file.watch=true
     - --entrypoints.web.address=:80
     - --entrypoints.websecure.address=:443
     - --entrypoints.web.forwardedHeaders.insecure=true 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/dynamic:/etc/traefik/dynamic
    networks:
      - proxy
    depends_on:
      authelia:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.vinicius-gpl.com`)
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=authelia-forwardauth@docker

  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.vinicius-gpl.com`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.middlewares=authelia-forwardauth@docker

networks:
  proxy:
    external: true
    name: traefik_proxy
