server:
  address: tcp://0.0.0.0:9091

log:
  level: info

jwt_secret: troca_por_um_secret_aleatorio_longo

default_redirection_url: https://vinicius-gpl.com

session:
  secret: troca_por_outro_secret_aleatorio
  cookies:
    - name: authelia_session
      domain: vinicius-gpl.com
      authelia_url: https://auth.vinicius-gpl.com
      expiration: 1h
      inactivity: 5m

storage:
  encryption_key: troca_por_mais_um_secret_32_chars
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notifications.txt

access_control:
  default_policy: deny
  rules:
    - domain: auth.vinicius-gpl.com
      policy: bypass
    - domain: "*.vinicius-gpl.com"
      policy: one_factor

authentication_backend:
  file:
    path: /config/users.yml
