services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped

    ports:
      - "8080:80"

    environment:
      JWT_ENABLED: ${JWT_ENABLED}
      JWT_SECRET: ${JWT_SECRET}

    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_logs:/var/log/onlyoffice
      - onlyoffice_fonts:/usr/share/fonts

volumes:
  onlyoffice_data:
  onlyoffice_logs:
  onlyoffice_fonts:
