networks:
  net:
    name: netdata_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  proxy:
    external: true

services:
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    hostname: netdata
    restart: always
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      net:
        ipv4_address: 172.28.0.2
      proxy:

volumes:
  netdata_config:
  netdata_lib:
  netdata_cache:
